# This is where you would override any of the default Mack configuration settings,
# as well as create your own settings. The configuration settings for your environment
# can be dumped out using this rake task:
# 
#   rake mack:dump:config#<environment>
# 
# Configuration parameters can be used in your application like such:
# 
#   app_config.<setting_name>
# 
# Nested parameters can be defined using ::.
# 
# Examples:
# default.yml:
#   default_time_limit: <%= 15.minutes %>
#   api::timeout_limit: <%= 15.seconds %>
# 
# app_config.default_time_limit # => 900
# app_config.api.timeout_limit # => 15


whiny_config_missing: false

mack::session_id: _macker-guide_session_id

mack::testing_framework: rspec

default_secret_key: S8R6TL5QKHJDFBFLLRRZ8NFLS5SL7NR4XFT57N6NLFXXPGBZM8C4WMRQMWRQQSXXZKTNAELB7F5JM4ZN

# Mack provides RJS support through mack-javascript gem.
# In order to have RJS support, you will need to perform the following steps:
# 1.  Uncomment the code below, and make sure that the framework is the one you want to use
# 2.  run:  rake generate:javascript
# mack::js_framework: jquery

# mack::use_sessions: false
        
