mack::site_domain: http://www.mackery.com
log_level: error
use_page_caching: true

cachetastic_default_options:
  debug: false
  adapter: file
  default_expiry: <%= 24.hours %>
  store_options:
    dir: <%= File.join(Mack.root, "tmp") %>
  logging:
    # n number of logs can be configured for a cache
    # their names can be anything you want, it's doesn't matter
    logger_1:
      # this sets the type of log you want to write to.
      # right now the only two options are file and console
      type: file
      # if the type is file, you need to configure where the log file is to be written.
      file: log/memcached.log
      # this sets the level of logging for this cache
      level: error

# cachetastic_default_options:
#     # this will dump into the log, configuration info for each cache, as well as the .inspect
#     # for each object returned from the cache
#     debug: false
#     # this is the type of file store to be used for this cache.
#     # more adapters can be developed and plugged in as desired
#     adapter: memcache
#     # this will marshall objects into and out of the store.
#     marshall_method: none
#     # this sets how long objects will live in the cache before they are auto expired.
#     default_expiry: <%= 24.hours %>
#     # when setting objects into the cache the expiry_swing is +/- to the expiry time.
#     # example: if the expiry time is 1 hour, and the swing is 15 minutes,
#     # objects will go into the cache with an expiry time sometime between 45 mins and 75 mins.
#     expiry_swing: <%= 15.minutes %>
#     # these options get passed on directly to the store.
#     store_options: # listed below are options for memcache
#       c_threshold: 10_000
#       compression: true
#       debug: false
#       readonly: false
#       urlencode: false
#     # configure logging for this cache:
#     logging:
#       # n number of logs can be configured for a cache
#       # their names can be anything you want, it's doesn't matter
#       logger_1:
#         # this sets the type of log you want to write to.
#         # right now the only two options are file and console
#         type: file
#         # if the type is file, you need to configure where the log file is to be written.
#         file: log/memcached.log
#         # this sets the level of logging for this cache
#         level: error
#     # set the servers to be used for memcache
#     servers:
#       - 127.0.0.1:11211
